  File "git\moto_dynamodb2_issue\.venv\lib\site-packages\moto\dynamodb2\models\__init__.py", line 1397, in get_item
    raise ValueError("No table found")"# moto_dynamodb2_issue" 
